title: schema.yaml - schema des colections dans MongoDB
doc: |
  contient principalement le schema de la collection administration
  le réel schéma est défini dans dessin.inc.php
schema:
  administration:
    _id: no SIREN
    adresseNorm:
      L1_NORMALISEE
      L2_NORMALISEE
      L3_NORMALISEE
      L4_NORMALISEE
      L5_NORMALISEE
      L6_NORMALISEE
      L7_NORMALISEE
    adresseDecl:
      L1_DECLAREE
      L2_DECLAREE
      L3_DECLAREE
      L4_DECLAREE
      L5_DECLAREE
      L6_DECLAREE
      L7_DECLAREE
    adresse:
      NUMVOIE
      INDREP
      TYPVOIE
      LIBVOIE
      CODPOS
      CEDEX
    loc:
      RPET
      LIBREG
      DEPET
      ARRONET
      CTONET
      COMET
      LIBCOM
      DU
      TU
      UU
      EPCI
      TCD
      ZEMET
    infoEtab:
      NIC
      SIEGE
      ENSEIGNE
      IND_PUBLIPO
      DIFFCOM
      AMINTRET
    caractEtab:
      NATETAB
      LIBNATETAB
      APET700
      LIBAPET
      DAPET
      TEFET
      LIBTEFET
      EFETCENT
      DEFET
      ORIGINE
      DCRET
      DDEBACT
      ACTIVNAT
      LIEUACT
      ACTISURF
      SAISONAT
      MODET
      PRODET
      PRODP
      ART
      AUXILT
    idEntreprise:
      NOMEN_LONG
      SIGLE
      NOM
      PRENOM
      CIVILITE
      RNA
    infoSiege:
      NICSIEGE
      RPEN
      DEPCOMEN
      ADR_MAIL
    caractEntreprise:
      NJ
      LIBNJ
      APEN700
      LIBAPEN
      DAPEN
      APRM
      ESS DATEESS TEFEN LIBTEFEN EFENCENT DEFEN CATEGORIE DCREN AMINTREN MONOACT MODEN PRODEN
      ESAANN TCA ESAAPEN ESASEC1N ESASEC2N ESASEC3N ESASEC4N
    donneesMaj:
      VMAJ
      VMAJ1
      VMAJ2
      VMAJ3
      DATEMAJ
    histos:
      - DATEHISTO: date de la mise à jour
        {champ}: ancienne valeur pour {champ} en cas de modif
    suppression?: si l'entité a été supprimée alors date de suppression, sinon ce champ n'existe pas
  
  historique:
  
  erreur:
  
  genealogie: